version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/src:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: feedbackdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./php/src/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build: ./php
    command: php /var/www/html/worker.php
    depends_on:
      - rabbitmq
      - php

volumes:
  mysql_data:
